function interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var)

f=figure('Name','Stabilizator cu Dioda Zenner',... 
 'Units','normalized',...
 'Position', [0.1, 0.1, 0.7, 0.7],...
 'Color',[ 0.25 0.80 0.54],...
 'NumberTitle','off');
%------------------------------------------------------------------------------------------------------------------
%--------------------meniu documentatie------------------------------------------------
f=uimenu('Label','Documentatie');
f1=uimenu(f,'Label','Circuite','Separator','on');
f1_1=uimenu(f1,...
       'Label','Stabilizator cu Dz');
   f1_11=uimenu(f1_1,...
    'Label','Circuit',...
    'Callback','open_zener'); 
f1_2=uimenu(f1,...
       'Label','Stabilizator cu Dz +tranzistor');
  f1_12=uimenu(f1_2,...
    'Label','Circuit',...
    'Callback','open_zener1');
f1_3=uimenu(f1,...
       'Label','Stabilizator cu Dz +tranzistor+A.O.');
  f1_13=uimenu(f1_3,...
    'Label','Varianta 1');
      f0_13=uimenu(f1_13,...
    'Label','Circuit',...
    'Callback','open_zener3');
  f2_13=uimenu(f1_3,...
    'Label','Varianta 2');
     f3_13=uimenu(f2_13,...
    'Label','Circuit',...
    'Callback','open_zener3');
f2=uimenu(f,'Label','DataSheet','Separator','on');
a=uimenu(f2,...
       'Label','Dioda Zener 1N4733A',...
       'Callback','zener');
b=uimenu(f2,...
    'Label','Tranzistor 2N3904',...
    'Callback','tranzistor');
f3=uimenu(f,'Label','Curs CEF','Separator','on',...
    'Callback','curs');
f4=uimenu(f,'Label','Tutorial','Separator','on',...
    'Callback','tutorial');
%--------------------------------------------------------------------------------------
f5=uimenu(f,'Label','Formule','Separator','on',...
    'Callback','formule');
%--------------------------------------------------------------------------------------
pop=uicontrol('Style','popupmenu',...
 'Units','normalized',...
 'Position',[0.8 0.7 0.14 0.09],...
 'foregroundcolor','black',...
 'String','Stabilizator Dz|Stabilizator Dz +Tranzistor|Stabiliator Dz+A.O.',...
 'Value',ex,...
 'Callback','ex=(get(gco,''value'')),close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var);');

%---------------------------------------------------------------------------------------------------------------------
%--------------------------------tensiunea de alimentare----------------------

V_min_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.0 0.5 0.1 0.03],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Vi_min');
Vmin_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.1 0.49 0.1 0.04],...
 'foregroundcolor','black',...
 'String',Vi_min,...
 'Callback','Vi_min=str2num(get(gco,''string'')),close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var);');

V_max_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.0 0.4 0.1 0.03],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Vi_max');
Vmax_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.1 0.39 0.1 0.04],...
 'foregroundcolor','black',...
 'String',Vi_max,...
 'Callback','Vi_max=str2num(get(gco,''string'')),close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var);');

%------------parametrii diodei zener---------------------------

zener=uibuttongroup('Visible','on',...
 'BackgroundColor',[0.25 0.80 0.54],...
'ForegroundColor','black',...
 'Title','Prametrii diodei Zener:1N4733A',...
 'FontSize',10,...
'TitlePosition','centertop',...
 'Tag','text',...
 'Tag','edit',...
 'Position',[0.48 0.66 0.25 0.3]);
%----------------------------------------------------------------------------------

Vz_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.0 0.6 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Vz',...
 'Parent',zener);


Vz_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.2 0.78 0.1 0.1],...
 'foregroundcolor','black',...
 'String',Vz,...
 'Callback','',...
 'Enable','off',...
  'Parent',zener);
%----------------------------------------------------------------------------------

Iz_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.2 0.49 0.13 0.1],...
 'foregroundcolor','black',...
 'String',Iz,...
 'Callback','Iz=str2num(get(gco,''string'')),close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var);',...
  'Parent',zener,...
  'Enable','off');


Iz_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.0 0.3 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Iz',...
 'Parent',zener);

%----------------------------------------------------------------------------------

IR_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.6 0.77 0.1 0.1],...
 'foregroundcolor','black',...
 'String',Ir,...
 'Callback','Ir=str2num(get(gco,''string'')),close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var);',...
  'Parent',zener,...
  'Enable','off');


IR_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.5 0.78 0.1 0.1],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','IR',...
 'Parent',zener);

rz_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.6 0.48 0.1 0.1],...
 'foregroundcolor','black',...
 'String',rz,...
 'Enable','off',...
 'Callback','rz=str2num(get(gco,''string'')),close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var);',...
  'Parent',zener);


rz_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.5 0.5 0.1 0.1],...
 'backgroundcolor',[ 0.25 0.80 0.58],...
 'foregroundcolor','black',...
 'FontSize',12,...
 'String','rz',...
 'Parent',zener);




%--------------------------------------------------------------------------------------
switch ex

    case 1
RL_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.2 0.4 0.1 0.03],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','RL');
RL_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.3 0.39 0.1 0.04],...
 'foregroundcolor','black',...
 'String',RL,...
 'Callback','RL=str2num(get(gco,''string'')),close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var);');

      
x= imread('zener.JPG');
h = image(x);
set(gca, 'Position', [0.05, 0.63, 0.35, 0.35]);
axis off;
%------------------------------butoane----------------------------------------
%calculul rezistentei serie
Rs_min=(Vi_min-Vz)/Iz;
Rs_max=(Vi_max-Vz)/Iz;
Rs=max(Rs_min,Rs_max)    %rezistenta serie


Ii=Vi/Rs;
Iout=Ii-Iz;
Vout=RL.*Iout;
   

Rs_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.2 0.5 0.1 0.03],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Rs');
Rs_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.3 0.49 0.1 0.04],...
 'foregroundcolor','black',...
 'String',Rs,...
 'Enable','off',...
 'Callback','Rs=str2num(get(gco,''string'')),close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var);');

%----------------------grafice----------------------------------------------------------
subplot(337);
Vi=Vi_min:1:Vi_max;
Ii=Vi/Rs;
plot(Ii,Vi,'r');
grid on;
xlabel('Curent[A]');
ylabel('Tensiune[V]');
title('Tensiune de alimentare');


subplot(338);
Iout=Ii-Iz;
Vout=RL.*Iout;
for i=1:length(Vi)
if Vout(i)>Vz
    Vout(i)=Vz;
else Vout(i)=Vout(i);
end
if Vout(i)<0.7
    Vout(i)=0.7;
else Vout(i)=Vout(i);
end
end
plot(Vi,Vout);
xlabel('Tensiune de alimentare[V]');
ylabel('Tensiune de iesire[V]');
title('Tensiune stabilizata');
grid on;

%--------------------------------caractesristica zener-------------------------------------------------------------------------------------

ck4=uicontrol('Style','check',...
              'Units','normalized',...
              'Position',[0.45 0.45 0.18 0.05],...
              'Value',ck,...
              'String','Caracteristica Curent-Tensiune',...
              'Callback','ck=1,close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var)');

if ck==1
set(ck4,'value',1); 
set(ck4, 'Callback','ck=0,close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var)');

Iz_min = 10e-6; 
Iz_max = 178e-3;  
VR = 1;  % tensiunea polarizare inversa 
IF = logspace(log10(Iz_min), log10(Iz_max), 100);
VF = Vz + IF * rz;  
VR = logspace(log10(Vz),log10(VR), 100);
IR = -(VR - Vz) / rz;%curent polarizare inversa

subplot(336);
semilogx(IF, VF, 'LineWidth', 2);
title('Polarizare directa');
ylabel('Curent dioda zener');
xlabel('Tensiune dioda zener');
grid on;

subplot(339);
plot(VR, IR, 'LineWidth', 2);
title('Polarizare inversa');
ylabel('Curent dioda zener');
xlabel('Tensiune dioda zener');
grid on;
end

%-----------------------------------------------------------------
    case 2

RL_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.2 0.4 0.1 0.03],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','RL');
RL_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.3 0.39 0.1 0.04],...
 'foregroundcolor','black',...
 'String',RL,...
 'Callback','RL=str2num(get(gco,''string'')),close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var);');
    
x= imread('zener1.JPG');
h = image(x);
set(gca, 'Position', [0.05, 0.63, 0.35, 0.35]);
axis off;
%-------------------------------------------------------------------------------
tranzistor=uibuttongroup('Visible','on',...
 'BackgroundColor',[0.25 0.80 0.54],...
'ForegroundColor','black',...
 'Title','Prametrii tranzistorului:2N3904',...
 'FontSize',10,...
'TitlePosition','centertop',...
 'Tag','text',...
 'Tag','edit',...
 'Position',[0.72 0.26 0.25 0.3]);
%---------------parametrii tranzistorului----------------------------_
Vbc_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.0 0.6 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Vbc',...
 'Parent',tranzistor);


Vbc_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.2 0.78 0.1 0.1],...
 'foregroundcolor','black',...
 'String',Vbc,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);
Vbe_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.0 0.35 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Vbc',...
 'Parent',tranzistor);


Vbe_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.2 0.55 0.1 0.1],...
 'foregroundcolor','black',...
 'String',Vbe,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);

Vce_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.0 0.1 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Vce',...
 'Parent',tranzistor);


Vce_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.2 0.26 0.1 0.1],...
 'foregroundcolor','black',...
 'String',Vce,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);

Ic_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.4 0.6 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Ic',...
 'Parent',tranzistor);


Ic_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.6 0.78 0.1 0.1],...
 'foregroundcolor','black',...
 'String',Ic,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);
beta_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.4 0.1 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','beta',...
 'Parent',tranzistor);


beta_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.6 0.26 0.1 0.1],...
 'foregroundcolor','black',...
 'String',beta,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);
Ib=Ic/beta;
Ib_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.4 0.35 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Ib',...
 'Parent',tranzistor);


Ib_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.6 0.54 0.15 0.1],...
 'foregroundcolor','black',...
 'String',Ib,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);
%Ic=Io

%----------------------grafice----------------------------------------------------------
subplot(337);
Vi=Vi_min:1:Vi_max;
Rs=max((Vi-Vz)./(Iz-Ib));%calculul rezistentei serie
Ii=Vi/Rs;
plot(Ii,Vi,'r');
grid on;
xlabel('Curent[A]');
ylabel('Tensiune[V]');
title('Tensiune de alimentare');

%--------------------------------------------------------------------------------
subplot(338);
Iout=Ic;
Vout=Vz-Vbe;
for i=1:length(Vi)
if Vi(i)<Vz 
    Vout(i)=Vi(i);
else
Vout(i)=Vz-Vbe;
end
end
plot(Vi,Vout.* ones(size(Vi)),'b');
xlabel('Tensiune de alimentare[V]');
ylabel('Tensiune de iesire[V]');
title('Tensiune stabilizata');
grid on;
disp(Vout);
%-----rezistenta serie-------
Rs_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.2 0.5 0.1 0.03],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Rs');
Rs_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.3 0.49 0.1 0.04],...
 'foregroundcolor','black',...
 'String',Rs,...
 'Enable','off',...
 'Callback','Rs=str2num(get(gco,''string'')),close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var);');
%----------------------------------------------------------------------------------------------------------------------------------
    case 3
ck2=uicontrol('Style','check',...
              'Units','normalized',...
              'Position',[0.8 0.1 0.18 0.05],...
              'Value',var,...
              'String','Varianta 1',...
              'Callback','var=1,close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var)');
if var==0
     set(ck2,'value',0);
x= imread('zener3.JPG');
h = image(x);
set(gca, 'Position', [0.01, 0.56, 0.43, 0.43]);
axis off;
Vi=Vi_min:1:Vi_max;
Rs=max((Vi-Vz)./Iz);%calculul rezistentei serie
Rs_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.2 0.5 0.1 0.03],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Rs');
Rs_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.3 0.49 0.1 0.04],...
 'foregroundcolor','black',...
 'String',Rs,... 
 'Enable','off',...
 'Callback','Rs=str2num(get(gco,''string'')),close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var);');
%--------------------------------------------------------------------------------
RL_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.2 0.4 0.1 0.03],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','RL');
RL_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.3 0.39 0.1 0.04],...
 'foregroundcolor','black',...
 'String',RL,...
 'Callback','RL=str2num(get(gco,''string'')),close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var);');
%-------------------------------------------------------------------------------
tranzistor=uibuttongroup('Visible','on',...
 'BackgroundColor',[0.25 0.80 0.54],...
'ForegroundColor','black',...
 'Title','Prametrii tranzistorului:2N3904',...
 'FontSize',10,...
'TitlePosition','centertop',...
 'Tag','text',...
 'Tag','edit',...
 'Position',[0.72 0.26 0.25 0.3]);
%---------------parametrii tranzistorului----------------------------_
Vbc_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.0 0.6 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Vbc',...
 'Parent',tranzistor);


Vbc_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.2 0.78 0.1 0.1],...
 'foregroundcolor','black',...
 'String',Vbc,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);
Vbe_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.0 0.35 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Vbc',...
 'Parent',tranzistor);


Vbe_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.2 0.55 0.1 0.1],...
 'foregroundcolor','black',...
 'String',Vbe,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);

Vce_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.0 0.1 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Vce',...
 'Parent',tranzistor);


Vce_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.2 0.26 0.1 0.1],...
 'foregroundcolor','black',...
 'String',Vce,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);

Ic_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.4 0.6 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Ic',...
 'Parent',tranzistor);


Ic_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.6 0.78 0.1 0.1],...
 'foregroundcolor','black',...
 'String',Ic,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);
beta_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.4 0.1 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','beta',...
 'Parent',tranzistor);


beta_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.6 0.26 0.1 0.1],...
 'foregroundcolor','black',...
 'String',beta,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);
Ib=Ic/beta;
Ib_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.4 0.35 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Ib',...
 'Parent',tranzistor);


Ib_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.6 0.54 0.15 0.1],...
 'foregroundcolor','black',...
 'String',Ib,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);
subplot(337);
Vi=Vi_min:1:Vi_max;
Rs=max((Vi-Vz)./Iz);%calculul rezistentei serie
Ii=Vi/Rs;
plot(Ii,Vi,'r');
grid on;
xlabel('Curent[A]');
ylabel('Tensiune[V]');
title('Tensiune de alimentare');

subplot(338);
Vout=Vz;
for i=1:length(Vi)
if Vi(i)<Vz 
    Vout(i)=Vi(i);
else
Vout(i)=Vz;
end
end
plot(Vi,Vout.* ones(size(Vi)),'b');
xlabel('Tensiune de alimentare[V]');
ylabel('Tensiune de iesire[V]');
title('Tensiune stabilizata');
grid on;
disp(Vout);
end
if var==1
 set(ck2,'value',1,'string','Varianta 2');
 set(ck2, 'Callback','var=0,close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var)');

x= imread('zener2.JPG');
h = image(x);
set(gca, 'Position', [0.05, 0.63, 0.35, 0.35]);
axis off;

%---------------------------------------------------------------

    

R1_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.2 0.5 0.1 0.03],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','R1');
R1_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.3 0.49 0.1 0.04],...
 'foregroundcolor','black',...
 'String',R1,...
 'Callback','R1=str2num(get(gco,''string'')),close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var);');
 
R2_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.2 0.4 0.1 0.03],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','R2');
R2_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.3 0.39 0.1 0.04],...
 'foregroundcolor','black',...
 'String',R2,...
 'Callback','R2=str2num(get(gco,''string'')),close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var);');
Vi=Vi_min:1:Vi_max;
Rs=max((Vi-Vz)./Iz);%calculul rezistentei serie
Rs_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.45 0.45 0.1 0.03],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Rs');
Rs_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.55 0.45 0.1 0.04],...
 'foregroundcolor','black',...
 'String',Rs,... 
 'Enable','off',...
 'Callback','Rs=str2num(get(gco,''string'')),close;interfata(Vz,Vi_min,Vi_max,ex,ck,RL,Iz,Ir,rz,Vi,Vbc,Vbe,Vce,Ic,beta,R1,R2,var);');

%-------------------------------------------------------------------------------
tranzistor=uibuttongroup('Visible','on',...
 'BackgroundColor',[0.25 0.80 0.54],...
'ForegroundColor','black',...
 'Title','Prametrii tranzistorului:2N3904',...
 'FontSize',10,...
'TitlePosition','centertop',...
 'Tag','text',...
 'Tag','edit',...
 'Position',[0.72 0.26 0.25 0.3]);
%---------------parametrii tranzistorului----------------------------_
Vbc_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.0 0.6 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Vbc',...
 'Parent',tranzistor);


Vbc_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.2 0.78 0.1 0.1],...
 'foregroundcolor','black',...
 'String',Vbc,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);
Vbe_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.0 0.35 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Vbc',...
 'Parent',tranzistor);


Vbe_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.2 0.55 0.1 0.1],...
 'foregroundcolor','black',...
 'String',Vbe,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);

Vce_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.0 0.1 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Vce',...
 'Parent',tranzistor);


Vce_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.2 0.26 0.1 0.1],...
 'foregroundcolor','black',...
 'String',Vce,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);

Ic_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.4 0.6 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Ic',...
 'Parent',tranzistor);


Ic_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.6 0.78 0.1 0.1],...
 'foregroundcolor','black',...
 'String',Ic,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);
beta_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.4 0.1 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','beta',...
 'Parent',tranzistor);


beta_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.6 0.26 0.1 0.1],...
 'foregroundcolor','black',...
 'String',beta,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);
Ib=Ic/beta;
Ib_text=uicontrol('Style','text', ...
 'Units','normalized',...
 'Position',[0.4 0.35 0.2 0.3],...
 'backgroundcolor',[ 0.25 0.80 0.54],...
 'foregroundcolor','black',...
 'FontSize',13,...
 'String','Ib',...
 'Parent',tranzistor);


Ib_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.6 0.54 0.15 0.1],...
 'foregroundcolor','black',...
 'String',Ib,...
 'Callback','',...
 'Enable','off',...
  'Parent',tranzistor);

subplot(337);
Vi=Vi_min:1:Vi_max;
Rs=max((Vi-Vz)./(Iz-Ib));%calculul rezistentei serie
Ii=Vi/Rs;
plot(Ii,Vi,'r');
grid on;
xlabel('Curent[A]');
ylabel('Tensiune[V]');
title('Tensiune de alimentare');

subplot(338);
for i=1:length(Vi)
if Vi(i)<Vz 
    Vout(i)=Vi(i);
else
Vout(i)=(1+R1/R2)*Vz;
end
end
plot(Vi,Vout.* ones(size(Vi)),'b');
xlabel('Tensiune de alimentare[V]');
ylabel('Tensiune de iesire[V]');
title('Tensiune stabilizata');
grid on;
disp(Vout);

end

end  
