function interfata(A1,A2,A3,f1,f2,f3,N,t,ex,comp)


Fig=figure('Name','Interfata',... %---Numele ferestrei---%
 'Units','normalized',...%---Unitatile de masura – 0->1-%
 'Position',[.1 .1 .5 .5],...%---Pozitia ferestrei pe ecran
 'NumberTitle','off'); %---Numarul ferestrei - nu se atribuie---%

A1_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.0 0.9 0.16 0.05],...
 'backgroundcolor','w',...
 'foregroundcolor','black',...
 'String','A1');
A2_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.0 0.80 0.16 0.05],...
 'backgroundcolor','w',...
 'foregroundcolor','black',...
 'String','A2');
A3_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.0 0.70 0.16 0.05],...
 'backgroundcolor','w',...
 'foregroundcolor','black',...
 'String','A3');
A1_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.2 0.9 0.16 0.05],...
 'foregroundcolor','b',...
 'String',A1,...
 'Callback','A1=str2num(get(gco,''string'')),close;interfata(A1,A2,A3,f1,f2,f3,N,t,ex,comp)');
 
A2_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.2 0.8 0.16 0.05],...
 'foregroundcolor','b',...
 'String',A2,...
 'Callback','A2=str2num(get(gcbo,''string'')),close;interfata(A1,A2,A3,f1,f2,f3,N,t,ex,comp)');
 

A3_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.2 0.7 0.16 0.05],...
 'foregroundcolor','b',...
 'String',A3,...
 'Callback','A3=str2num(get(gcbo,''string'')),close;interfata(A1,A2,A3,f1,f2,f3,N,t,ex,comp)');
 
f1_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.4 0.9 0.16 0.05],...
 'backgroundcolor','w',...
 'foregroundcolor','black',...
 'String','f1');

f2_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.4 0.8 0.16 0.05],...
 'backgroundcolor','w',...
 'foregroundcolor','black',...
 'String','f2');

f3_text=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.4 0.7 0.16 0.05],...
 'backgroundcolor','w',...
 'foregroundcolor','black',...
 'String','f3');

f1_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.6 0.9 0.16 0.05],...
 'foregroundcolor','b',...
 'String',f1,...
 'Callback','f1=str2num(get(gcbo,''string'')),close;interfata(A1,A2,A3,f1,f2,f3,N,t,ex,comp)');


f2_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.6 0.8 0.16 0.05],...
 'foregroundcolor','b',...
 'String',f2,...
 'Callback','f2=str2num(get(gcbo,''string'')),close;interfata(A1,A2,A3,f1,f2,f3,N,t,ex,comp)');

f3_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.6 0.7 0.16 0.05],...
 'foregroundcolor','b',...
 'String',f3,...
 'Callback','f3=str2num(get(gco,''string'')),close;interfata(A1,A2,A3,f1,f2,f3,N,t,ex,comp)');
ftab = [f1 f2 f3];
f0=gcd(f1,f2);
f = gcd(f0,f3); 
disp(f);
Tend = 1/f;
Tpas = 1/(max(ftab)); 
t=0:Tpas/100:N*Tend;
%semnale
m=A1*cos(2*f1*pi*t)+A2*cos(2*f2*pi*t);
c=A3*cos(2*f3*pi*t);
%reprezentare grafica
subplot(312);

plot(t,m,'r');
hold on;
plot(t,c,'b');
ylabel('Amplitudine'); 
xlabel('timp');
legend('m','c') 

pop=uicontrol('Style','popup',...
           'Units','normalized',...
           'Position',[0.8 0.85 0.2 0.06],...
           'string','Adunare|Scadere|Produs|Other value',...
           'Value',ex,...
           'Callback','ex=(get(gcbo,''value'')),close;interfata(A1,A2,A3,f1,f2,f3,N,t,ex,comp)')

switch ex

    case 1
s=m+c;

subplot(313);

plot(t,s);

ylabel('Amplitudine'); 
xlabel('timp');
title('Semnalul s');
    case 2
        s=m-c;

subplot(313);

plot(t,s);
hold on; 
ylabel('Amplitudine'); 
xlabel('timp');
title('Semnalul s');
    case 3

   s=m.*c;
subplot(313);

plot(t,s);
hold on; 
ylabel('Amplitudine'); 
xlabel('timp');
title('Semnalul s');

    case 4



subplot(313);


hold on; 
ylabel('Amplitudine'); 
xlabel('timp');
title('Semnalul s');

end


Comp=uicontrol('Style','Checkbox',...
 'Units','normalized',...
 'String','Comparator',...
 'BackgroundColor','w',...
 'Position', [0.8 .7 .1 .06],...
 'Value',0,...
 'Callback','comp=1,close;interfata(A1,A2,A3,f1,f2,f3,N,t,ex,comp)');

Vpoz = 10;
Vneg = -10;


if comp == 0 
set(pop,'Enable','on');
switch ex
case 1
s = m + c; 
    case 2
s = m - c; 
    case 3
s = m.*c;
end
elseif comp== 1 
set(pop,'Enable','off');
set(Comp,'value',1);
for i=1:length(t)
    if m(i)>c(i)
s(i) = Vpoz;
    else
s(i) = Vneg;

end

end

end

subplot(313);

plot(t,s,'g');
ylabel('Amplitudine');
xlabel('timp');
title('Semnalul s');

minim=0;
maxim=10;
uicontrol('Style','slider',...
           'Units','normalized',...
           'Position',[0.05 0.42 .02 .2],...
           'Min',minim,'Max',maxim,...
           'SliderStep',[1/(maxim-minim) 10/(maxim-minim)],...
           'value',N,...
           'Callback','N=round(get(gcbo,''value'')),close;interfata(A1,A2,A3,f1,f2,f3,N,t,ex,comp)');

N_edit=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.02 0.42 .02 .2],...
 'foregroundcolor','b',...
 'String',N,...
 'Callback','N=str2num(get(gcbo,''string'')),close;interfata(A1,A2,A3,f1,f2,f3,N,t,ex,comp)');




